GET http://localhost:3000/tasks

###
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "empty description",
  "description": ""
}

###
GET http://localhost:3000/tasks/08521ce7-b958-4e19-835c-bd5f03d0ad45
###
DELETE http://localhost:3000/tasks/08521ce7-b958-4e19-835c-bd5f03d0ad45
###
PATCH  http://localhost:3000/tasks/08521ce7-b958-4e19-835c-bd5f03d0ad45/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}
###
GET http://localhost:3000/tasks?status=OPEN&description=Test
