GET http://localhost:3000/tasks

###
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Test title 3",
  "description": "Test description 2"
}

###
GET http://localhost:3000/tasks/2893315ss3-a89a-403e-9869-03d945fdccd4
###
DELETE http://localhost:3000/tasks/del/0a95b762-f79f-4e12-8c43-2802af2434bf